<?php

/**
 * BaseVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $image_id
 * @property integer $value
 * @property Image $Image
 * 
 * @method integer getImageId()  Returns the current record's "image_id" value
 * @method integer getValue()    Returns the current record's "value" value
 * @method Image   getImage()    Returns the current record's "Image" value
 * @method Vote    setImageId()  Sets the current record's "image_id" value
 * @method Vote    setValue()    Sets the current record's "value" value
 * @method Vote    setImage()    Sets the current record's "Image" value
 * 
 * @package    MyHON
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote');
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}