<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/08 09:48:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=myhotornot',
  'username' => 'blogornot',
  'password' => 'blogornot',
  'name' => 'doctrine',
)),);
